Repository unicef/etools-partnership-management, pull requests merged in 2018-05, with the labels that each got.

#842 Fix fireEvent error on partner delete and type_of_assesment
  pmp/modules/app-modules/partners/components/partner-status.html
  pmp/modules/app-modules/partners/pages/financial-assurance/partner-financial-assurance.html
Labels: READY

#841 Fix agreement status issues
  pmp/modules/app-modules/agreements/components/agreement-status.html
  pmp/modules/app-modules/interventions/components/intervention-status.html
Labels: READY

#846 fix(indicator dialog): means of verfification field editable [ch5662]
  pmp/modules/app-modules/interventions/pages/details/components/results/cluster-indicator.html
  pmp/modules/app-modules/interventions/pages/details/components/results/non-cluster-indicator.html
Labels: READY

#847 Fix save user profile
  bower.json
  pmp/modules/layout/page-header.html
Labels: READY

#849 Fix persisiting files
  pmp/modules/app-modules/interventions/interventions-module.html
Labels: READY

#850 delete partner fix
  pmp/modules/app-modules/partners/data/partner-item-data.html
  pmp/modules/app-modules/partners/partners-module.html
Labels: READY, bug

#854 link partner name from PD details title to partner overview
  pmp/modules/app-modules/interventions/interventions-module.html
Labels: READY

#856 Display Programmatic Visits in Financial Assurance tab
  pmp/modules/app-modules/interventions/pages/overview/components/monitoring-visits-list.html
  pmp/modules/app-modules/interventions/pages/overview/intervention-overview.html
  pmp/modules/app-modules/partners/pages/financial-assurance/partner-financial-assurance.html
  pmp/modules/endpoints/endpoints.html
Labels: READY

#834 New Partner reporting requirements
  bower.json
  pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/hr/edit-hru-dialog.html
  pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/hr/hru-list.html
  pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/hr/humanitarian-reporting-req-cluster.html
  pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/hr/humanitarian-reporting-req-unicef.html
  pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/mixins/generate-quarterly-reporting-requirements-mixin.html
  pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/mixins/reporting-req-past-dates-check.html
  pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/mixins/reporting-requirements-common-mixin.html
  pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/partner-reporting-requirements.html
  pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/qpr/edit-qpr-dialog.html
  pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/qpr/qpr-list.html
  pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/qpr/quarterly-reporting-requirements.html
  pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/srr/add-edit-special-rep-req.html
  pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/srr/special-reporting-requirements.html
  pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/styles/reporting-requirements-lists-styles.html
  pmp/modules/app-modules/interventions/pages/details/components/results/non-cluster-indicator.html
  pmp/modules/app-modules/interventions/pages/details/intervention-details.html
  pmp/modules/app-modules/settings/components/disaggregation-list.html
  pmp/modules/config/app-constants.html
  pmp/modules/endpoints/endpoints.html
  pmp/modules/mixins/frontend-pagination-mixin.html
  pmp/modules/styles/grid-layout-styles.html
Labels: WIP

#855 Financial Assurance label and columns changes
  pmp/modules/app-modules/partners/pages/financial-assurance/partner-financial-assurance.html
  pmp/modules/app-modules/partners/pages/overview/partner-overview.html
  pmp/modules/app-modules/partners/partners-module.html
Labels: READY

#852 Fix dialog centering issue
  bower.json
  pmp/modules/app-modules/interventions/pages/details/components/results/indicator-dialog.html
  pmp/modules/app-modules/interventions/pages/details/components/results/indicator-dissaggregations.html
  pmp/modules/app-modules/interventions/pages/review-and-sign/components/fund-reservations/update-fr-numbers.html
  pmp/modules/app-modules/partners/pages/financial-assurance/partner-financial-assurance.html
Labels: READY

#857 Signedby validation remove, PD permissions and in amendment state updates
  pmp/app-shell.html
  pmp/modules/amendment-mode/amendment-mode-UI-mixin.html
  pmp/modules/amendment-mode/redux-in-amendment-mixin.html
  pmp/modules/app-modules/agreements/pages/details/agreement-details.html
  pmp/modules/app-modules/interventions/interventions-module.html
  pmp/modules/app-modules/interventions/mixins/intervention-permissions-mixin.html
  pmp/modules/app-modules/interventions/pages/details/components/agreement-selector.html
  pmp/modules/app-modules/interventions/pages/details/components/planned-budget.html
  pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/hr/edit-hru-dialog.html
  pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/hr/humanitarian-reporting-req-unicef.html
  pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/mixins/reporting-req-past-dates-check.html
  pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/partner-reporting-requirements.html
  pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/qpr/edit-qpr-dialog.html
  pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/qpr/quarterly-reporting-requirements.html
  pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/srr/special-reporting-requirements.html
  pmp/modules/app-modules/interventions/pages/details/components/results/applied-indicator.html
  pmp/modules/app-modules/interventions/pages/details/components/results/applied-indicators.html
  pmp/modules/app-modules/interventions/pages/details/components/results/expected-results.html
  pmp/modules/app-modules/interventions/pages/details/components/results/result-link-lower-results.html
  pmp/modules/app-modules/interventions/pages/details/intervention-details.html
  pmp/modules/app-modules/interventions/pages/review-and-sign/components/amendments/pd-amendments.html
  pmp/modules/app-modules/interventions/pages/review-and-sign/intervention-review-and-sign.html
  pmp/modules/mixins/amendment-mode-mixin.html
  pmp/modules/redux/etools-data-redux-store.html
  pmp/modules/redux/redux-permissions-updater-mixin.html
Labels: READY

#858 disable future dates for signed by fields
  pmp/modules/app-modules/agreements/pages/details/agreement-details.html
  pmp/modules/app-modules/interventions/pages/details/intervention-details.html
  pmp/modules/app-modules/interventions/pages/review-and-sign/intervention-review-and-sign.html
  pmp/modules/layout/components/etools-date-input.html
Labels: READY

#859 Fix date conversion
  pmp/modules/mixins/common-mixin.html
  pmp/modules/mixins/date-mixin.html
Labels: READY

#865 Update monitoring visits endpoint
  pmp/modules/app-modules/interventions/pages/overview/components/monitoring-visits-list.html
  pmp/modules/endpoints/endpoints.html
Labels: READY

#863 Cp structure updates
  bower.json
  pmp/modules/layout/components/etools-cp-structure.html
Labels: READY

#868 Reset disabled Cps on PD change
  pmp/modules/layout/components/etools-cp-structure.html
Labels: READY

#873 Fixes incorrect labels
  pmp/modules/app-modules/agreements/data/agreement-item-data.html
  pmp/modules/app-modules/agreements/pages/list/agreements-list.html
  pmp/modules/app-modules/interventions/data/intervention-item-data.html
  pmp/modules/app-modules/interventions/mixins/save-intervention-mixin.html
  pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/reporting-requirements-dialog.html
  pmp/modules/app-modules/interventions/pages/details/components/results/indicator-dialog.html
  pmp/modules/app-modules/interventions/pages/details/components/results/pd-lower-result-name.html
  pmp/modules/app-modules/interventions/pages/details/components/results/result-cp-output-and-ram-indicators.html
  pmp/modules/app-modules/partners/components/new-partner-dialog.html
  pmp/modules/app-modules/partners/data/partner-item-data.html
  pmp/modules/user/profile-operations-mixin.html
Labels: READY

#870 FR number eager validations fix
  pmp/modules/app-modules/interventions/pages/review-and-sign/components/fund-reservations/update-fr-numbers.html
Labels: READY

#872 Add Risk Rating filter
  pmp/modules/app-modules/partners/data/partners-list-data.html
  pmp/modules/app-modules/partners/pages/list/partners-list.html
  pmp/modules/redux/etools-data-redux-store.html
  pmp/modules/static-common-data/mixins/dropdowns-static-data.html
Labels: READY

#871 Feature pd list grant and donor
  pmp/modules/app-modules/agreements/pages/list/agreements-list.html
  pmp/modules/app-modules/interventions/data/interventions-list-data.html
  pmp/modules/app-modules/interventions/pages/list/interventions-list.html
  pmp/modules/app-modules/partners/pages/list/partners-list.html
  pmp/modules/mixins/list-filters-mixin.html
  pmp/modules/redux/etools-data-redux-store.html
  pmp/modules/static-common-data/mixins/dropdowns-pmp-data.html
Labels: READY

#874 Add revision number to bower.json on build
  .circleci/config.yml
  bower.json
Labels: READY

#875 PD filters, grants and donors updates
  pmp/modules/app-modules/interventions/data/interventions-list-data.html
  pmp/modules/app-modules/interventions/pages/list/interventions-list.html
Labels: READY

#864 Reporting requirements updates
  pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/hr/hru-list.html
  pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/hr/humanitarian-reporting-req-unicef.html
  pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/mixins/reporting-req-past-dates-check.html
  pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/mixins/reporting-requirements-common-mixin.html
  pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/partner-reporting-requirements.html
  pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/qpr/edit-qpr-dialog.html
  pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/qpr/qpr-list.html
  pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/qpr/quarterly-reporting-requirements.html
  pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/reporting-requirements-dialog.html
  pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/reporting-requirements.html
  pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/srr/add-edit-special-rep-req.html
  pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/srr/special-reporting-requirements.html
  pmp/modules/app-modules/interventions/pages/details/intervention-details.html
  pmp/modules/endpoints/endpoints.html
Labels: READY

#876 Assurance editable fields change
  pmp/modules/app-modules/interventions/pages/details/intervention-details.html
  pmp/modules/app-modules/partners/pages/financial-assurance/partner-financial-assurance.html
Labels: READY

#866 User notifications for partner details
  pmp/modules/app-modules/partners/pages/details/partner-details.html
Labels: READY

#877 PD locations export button
  pmp/modules/app-modules/interventions/interventions-module.html
  pmp/modules/config/app-constants.html
  pmp/modules/endpoints/endpoints.html
Labels: WIP

#878 circle ci revision number experiments
  .circleci/config.yml
Labels: WIP

#881 Add build date to bower.json
  .circleci/config.yml
  bower.json
Labels: READY

#880 reporting requirements fixes
  pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/qpr/edit-qpr-dialog.html
  pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/qpr/qpr-list.html
  pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/srr/special-reporting-requirements.html
Labels: READY

#882 PD details - locations dropdown behavior fix, style improvement
  pmp/modules/app-modules/interventions/pages/details/intervention-details.html
Labels: READY
