Repository unicef/etools-partnership-management, pull requests merged in 2018-07, with the labels that each got.

#911 Start date for HU Reporting Requirements
  bower.json
  pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/hr/edit-hru-dialog.html
  pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/hr/hru-list.html
  pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/hr/humanitarian-reporting-req-unicef.html
  pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/partner-reporting-requirements.html
Labels: READY

#922 Feature partner details updates
  pmp/modules/app-modules/partners/pages/details/partner-details.html
  pmp/modules/app-modules/partners/pages/financial-assurance/partner-financial-assurance.html
  pmp/modules/layout/components/etools-form-element-wrapper.html
  pmp/modules/mixins/risk-rating-mixin.html
  pmp/modules/styles/risk-rating-styles.html
Labels: READY

#923 Feature update partners assurance
  pmp/modules/app-modules/partners/pages/financial-assurance/partner-financial-assurance.html
Labels: READY

#927 Indicators updates
  pmp/modules/app-modules/interventions/pages/details/components/results/applied-indicator.html
  pmp/modules/app-modules/interventions/pages/details/components/results/cluster-indicator.html
  pmp/modules/app-modules/interventions/pages/details/components/results/indicator-dialog.html
  pmp/modules/app-modules/interventions/pages/details/components/results/mixins/indicators-common-mixin.html
  pmp/modules/app-modules/interventions/pages/details/components/results/mixins/save-indicator-mixin.html
  pmp/modules/app-modules/interventions/pages/details/components/results/non-cluster-indicator.html
Labels: READY

#925 HU start date fixes
  pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/hr/edit-hru-dialog.html
Labels: READY

#933 updated vendor-number [ch5617]
  pmp/modules/app-modules/partners/pages/details/partner-details.html
Labels: READY

#930 Partner contacts redesign
  pmp/modules/app-modules/partners/pages/details/components/add-edit-staff-members.html
  pmp/modules/app-modules/partners/pages/details/components/staff-members.html
  pmp/modules/app-modules/partners/pages/details/partner-details.html
  pmp/modules/app-modules/partners/partners-module.html
Labels: READY

#931 adjusted styling on etools-form-wrapper
  pmp/modules/app-modules/agreements/pages/details/agreement-details.html
  pmp/modules/app-modules/interventions/pages/details/components/agreement-selector.html
  pmp/modules/app-modules/interventions/pages/details/components/planned-budget.html
  pmp/modules/app-modules/interventions/pages/details/intervention-details.html
  pmp/modules/app-modules/interventions/pages/progress/intervention-progress.html
  pmp/modules/app-modules/partners/pages/details/partner-details.html
  pmp/modules/app-modules/reports/components/report-status.html
  pmp/modules/app-modules/reports/pages/progress/components/report-overall.html
  pmp/modules/app-modules/reports/pages/progress/components/sr-details.html
  pmp/modules/app-modules/reports/pages/progress/report-progress.html
  pmp/modules/app-modules/reports/pages/summary/report-summary.html
  pmp/modules/layout/components/etools-form-element-wrapper.html
Labels: READY

#935 Fix agreement status actions
  pmp/modules/app-modules/agreements/components/agreement-status.html
Labels: READY

#928 Agreement amendments redesign
  pmp/modules/app-modules/agreements/agreements-module.html
  pmp/modules/app-modules/agreements/pages/details/agreement-details.html
  pmp/modules/app-modules/agreements/pages/details/components/agreement-amendments.html
  pmp/modules/app-modules/agreements/pages/details/components/amendments/add-ag-amendment-dialog.html
  pmp/modules/app-modules/agreements/pages/details/components/amendments/agreement-amendments.html
  pmp/modules/app-modules/interventions/pages/review-and-sign/components/amendments/pd-amendments.html
  pmp/modules/styles/shared-styles.html
Labels: READY

#936 Partner contacts style updates
  pmp/modules/app-modules/partners/pages/details/components/add-edit-staff-members.html
  pmp/modules/app-modules/partners/pages/details/components/staff-members.html
Labels: READY

#934 Programmatic Visits-update When column data
  pmp/modules/app-modules/shared/components/monitoring-visits-list.html
Labels: READY

#924 Partner actual cash transfer for current year update
  pmp/modules/app-modules/partners/pages/list/partners-list.html
Labels: READY

#939 Partner contacts email readonly
  pmp/modules/app-modules/partners/pages/details/components/add-edit-staff-members.html
  pmp/modules/app-modules/partners/pages/details/components/staff-members.html
Labels: READY

#938 placeholder fixes
  pmp/modules/app-modules/interventions/pages/details/intervention-details.html
  pmp/modules/app-modules/interventions/pages/review-and-sign/intervention-review-and-sign.html
Labels: READY

#942 enable fields
  pmp/modules/app-modules/agreements/agreements-module.html
  pmp/modules/app-modules/interventions/mixins/modified-intervention-fields-mixin.html
Labels: API changes needed, WIP

#941 Special conditions PCA
  pmp/modules/app-modules/agreements/agreements-module.html
  pmp/modules/app-modules/agreements/pages/details/agreement-details.html
Labels: READY

#937 created reference-number year dropdown
  pmp/modules/app-modules/agreements/agreements-module.html
  pmp/modules/app-modules/agreements/pages/details/agreement-details.html
  pmp/modules/app-modules/interventions/interventions-module.html
  pmp/modules/app-modules/interventions/mixins/modified-intervention-fields-mixin.html
  pmp/modules/app-modules/interventions/pages/details/intervention-details.html
  pmp/modules/layout/components/year-dropdown.html
Labels: READY

#946 Feature warning msg
  pmp/modules/app-modules/interventions/pages/review-and-sign/components/amendments/add-amendment-dialog.html
  pmp/modules/layout/components/etools-warn-message.html
  pmp/modules/styles/app-theme.html
Labels: READY

#945 Names of UNICEF signatories
  pmp/modules/app-modules/agreements/agreements-module.html
  pmp/modules/app-modules/agreements/pages/details/agreement-details.html
  pmp/modules/app-modules/interventions/mixins/intervention-permissions-mixin.html
  pmp/modules/app-modules/interventions/mixins/modified-intervention-fields-mixin.html
  pmp/modules/app-modules/interventions/pages/review-and-sign/intervention-review-and-sign.html
Labels: READY, Wait for BE branch merge

#929 Core Values Assessments Redesign
  pmp/modules/app-modules/interventions/pages/details/components/results/applied-indicator.html
  pmp/modules/app-modules/partners/data/partner-item-data.html
  pmp/modules/app-modules/partners/pages/details/components/edit-core-values-assessment.html
  pmp/modules/app-modules/partners/pages/details/partner-details.html
  pmp/modules/app-modules/partners/partners-module.html
  pmp/modules/mixins/common-mixin.html
  pmp/modules/mixins/date-mixin.html
Labels: READY

#949 Risk rating bg color style fix
  pmp/modules/app-modules/partners/pages/financial-assurance/partner-financial-assurance.html
Labels: READY

#951 CVA updates
  pmp/modules/app-modules/partners/pages/details/partner-details.html
Labels: READY

#952 Fix 'When' column data
  pmp/modules/app-modules/shared/components/monitoring-visits-list.html
Labels: READY

#953 IE style fix
  pmp/modules/app-modules/partners/pages/details/components/staff-members.html
Labels: READY

#954 Sort CVA
  pmp/modules/app-modules/partners/pages/details/partner-details.html
  pmp/modules/styles/shared-styles.html
Labels: READY

#955 Rename When column
  pmp/modules/app-modules/shared/components/monitoring-visits-list.html
Labels: READY

#957 fixed hidden status of the edit icon for planned budget
  pmp/modules/app-modules/interventions/pages/details/components/planned-budget.html
Labels: READY

#959 Updates etools-profile-dropdown
  bower.json
Labels: READY

#958 break-word in CVA column
  pmp/modules/app-modules/partners/pages/details/partner-details.html
  pmp/modules/styles/shared-styles.html
Labels: READY

#926 New attachment field on PD amendment
  pmp/modules/app-modules/interventions/pages/review-and-sign/components/amendments/add-amendment-dialog.html
  pmp/modules/app-modules/interventions/pages/review-and-sign/components/amendments/pd-amendments.html
  pmp/modules/endpoints/endpoints.html
Labels: READY

#956 reference number year dropdown fixes
  pmp/modules/app-modules/agreements/agreements-module.html
  pmp/modules/app-modules/agreements/pages/details/agreement-details.html
  pmp/modules/app-modules/interventions/interventions-module.html
  pmp/modules/app-modules/interventions/pages/details/intervention-details.html
  pmp/modules/layout/components/year-dropdown.html
Labels: WIP

#960 Update locations endpoint
  pmp/modules/app-modules/interventions/pages/details/components/grouped-locations-dialog.html
  pmp/modules/endpoints/endpoints.html
Labels: READY
