Repository unicef/etools-partnership-management, pull requests merged in 2018-03, with the labels that each got.

#716 small lint fix: removed empty line
  pmp/app-elements/interventions/behaviors/fr-numbers-consistency-behavior.html
Labels: READY

#717 piwiki element version update
  bower.json
Labels: READY

#713 Eslint config additions & fixes
  .eslintrc.json
  express.js
  index.html
  package.json
  pmp/app-shell.html
  pmp/modules/app-modules/not-found/not-found.html
  pmp/modules/app-modules/partners/components/partner-status/partner-status.html
  pmp/modules/app-modules/partners/data/partner-item-data.html
  pmp/modules/app-modules/partners/partners-module.html
  pmp/modules/config/dexie-db-config.html
  pmp/modules/endpoints/endpoints.html
  pmp/modules/environment-flags/environment-flags.html
  pmp/modules/layout/components/countries-dropdown.html
  pmp/modules/layout/components/data-refresh-dialog.html
  pmp/modules/layout/components/etools-date-input.html
  pmp/modules/layout/components/etools-single-file.html
  pmp/modules/layout/components/etools-status/etools-status.html
  pmp/modules/layout/page-header.html
  pmp/modules/mixins/ajax-errors-parser-mixin.html
  pmp/modules/mixins/ajax-server-errors-mixin.html
  pmp/modules/mixins/common-mixin.html
  pmp/modules/mixins/event-helper-mixin.html
  pmp/modules/mixins/ie11-mixin.html
  pmp/modules/mixins/list-data-mixin.html
  pmp/modules/mixins/list-filters-mixin.html
  pmp/modules/mixins/repeatable-data-sets-mixin.html
  pmp/modules/redux/etools-data-redux-store.html
  pmp/modules/scripts/polyfils/es6-polyfils.html
  pmp/modules/static-common-data/static-common-data.html
  pmp/modules/user/profile-operations-mixin.html
  pmp/modules/user/user-data-mixin.html
  pmp/modules/user/user-data.html
  pmp/modules/user/user-permissions-mixin.html
  pmp/modules/validators/etools-iron-validator-mixin.html
  sw-precache-config.js
  test/index.html
Labels: Polymer 2 migration, READY

#715 Planned visits with quarters
  pmp/app-elements/interventions/intervention-planned-visits.html
Labels: READY

#718 Fix planned visits
  pmp/app-elements/interventions/intervention-planned-visits.html
Labels: READY

#719 Planned visits-adjust validation
  pmp/app-elements/interventions/intervention-planned-visits.html
Labels: READY

#720 Fix planned budget frs validations warnings on new pd page
  bower.json
  pmp/app-elements/interventions/intervention-planned-budget.html
  pmp/pages/page-interventions.html
Labels: READY

#707 Polymer2 build and serve
  .circleci/config.yml
  Dockerfile
  express.js
  index.html
  package.json
  polymer.json
Labels: Polymer 2 migration, READY

#726 pd export updates
  pmp/app-elements/interventions/interventions-list.html
  pmp/app-elements/page-header/page-content-header.html
  pmp/pages/page-interventions.html
Labels: enhancement

#727 linting fixes
  pmp/app-config/app-constants.html
  pmp/app-elements/agreements/agreement-details.html
  pmp/app-elements/interventions/expected-results/applied-indicator.html
  pmp/app-elements/interventions/intervention-planned-visits.html
  pmp/app-elements/page-header/page-header.html
  pmp/app-elements/partners/partners-data/partner-item-data.html
  pmp/app-elements/reports/elems/behaviors/disaggregation-field.html
  pmp/app-elements/reports/elems/behaviors/disaggregations.html
  pmp/app-elements/reports/elems/disaggregations/disaggregation-field.html
  pmp/app-elements/reports/elems/disaggregations/table-content/one-disaggregation.html
  pmp/app-elements/reports/elems/disaggregations/table-content/three-disaggregations.html
  pmp/app-elements/reports/elems/disaggregations/table-content/two-disaggregations.html
  pmp/app-elements/reports/elems/indicator-details.html
  pmp/app-elements/reports/elems/report-overall.html
  pmp/app-elements/reports/reports-list.html
  pmp/app-elements/settings/add-disaggregation-dialog.html
  pmp/pages/page-interventions.html
Labels: READY

#728 Financial Assurance Tab bug fix + styling change
  dev-reinstall.sh
  pmp/app-config/app-config.html
  pmp/app-elements/partners/partner-details.html
  pmp/app-elements/partners/partner-financial-assurance.html
  pmp/app-elements/partners/partners-data/partner-item-data.html
  pmp/pages/page-partners.html
  styles/app-theme.html
  styles/risk-rating-styles.html
Labels: READY

#730 pd currency init fix
  pmp/app-elements/interventions/intervention-planned-budget.html
Labels: READY

#733 clean risk rating colors
  styles/app-theme.html
Labels: READY

#731 Amendments to incorrect pd
  pmp/app-elements/interventions/amendments/add-amendment-dialog.html
  pmp/app-elements/interventions/amendments/intervention-amendments.html
Labels: READY

#735 Env flags updates
  pmp/modules/environment-flags/environment-flags-mixin.html
  pmp/modules/environment-flags/environment-flags.html
Labels: Polymer 2 migration, READY

#742 fix lint issues
  gulp-tasks/javascript.js
  pmp/app-elements/partners/assessments-items.html
  pmp/app-elements/partners/partner-financial-assurance.html
Labels: READY

#745 expected results updates, possible fix for 4429, error handling impro…
  pmp/app-behaviors/repeatable-data-sets-behavior.html
  pmp/app-elements/interventions/expected-results/behaviors/lower-results-behavior.html
  pmp/app-elements/interventions/expected-results/pd-lower-result-name.html
  pmp/app-elements/interventions/expected-results/result-link-lower-results.html
  pmp/app-elements/interventions/intervention-expected-results.html
Labels: READY

#746 FRs amount updates
  pmp/app-elements/interventions/behaviors/fr-numbers-consistency-behavior.html
Labels: READY

#739 Fix interventions amendments issues
  pmp/app-elements/interventions/amendments/intervention-amendments.html
  pmp/app-elements/interventions/intervention-data/intervention-item-data.html
  pmp/pages/page-interventions.html
Labels: READY

#747 Update add planned visits btn style
  pmp/app-elements/interventions/intervention-planned-visits.html
Labels: READY

#749 fix lower results add action
  pmp/app-behaviors/repeatable-data-sets-behavior.html
  pmp/app-elements/interventions/expected-results/behaviors/lower-results-behavior.html
  pmp/app-elements/interventions/expected-results/behaviors/results-behavior.html
  pmp/app-elements/interventions/intervention-expected-results.html
  pmp/app-elements/interventions/intervention-planned-visits.html
Labels: READY, bug

#748 Update PD export btn
  pmp/app-elements/etools-status/etools-action-button.html
  pmp/app-elements/interventions/expected-results/applied-indicator.html
  pmp/app-elements/interventions/interventions-list.html
  pmp/pages/page-interventions.html
Labels: READY

#740 Migrate settings page
  pmp/app-shell.html
  pmp/modules/app-modules/settings/components/add-disaggregation-dialog.html
  pmp/modules/app-modules/settings/components/disaggregation-list.html
  pmp/modules/app-modules/settings/settings-module.html
  pmp/modules/layout/components/etools-status/etools-status.html
  pmp/modules/scripts/polyfils/es6-polyfils.html
  pmp/modules/styles/app-theme.html
  pmp/modules/styles/required-field-styles.html
  pmp/modules/styles/shared-styles.html
  pmp/modules/toast-notifications/toast-notifications-mixin.html
Labels: Polymer 2 migration, READY

#750 locations field is not required on new pd page
  pmp/app-elements/interventions/behaviors/intervention-permissions-behavior.html
Labels: READY

#753 Disable currency edit in amendment mode
  pmp/app-elements/interventions/intervention-data/intervention-item-data.html
  pmp/app-elements/interventions/intervention-planned-budget.html
  pmp/pages/page-interventions.html
Labels: READY

#754 frs warning fixes
  pmp/app-elements/interventions/fr-numbers/intervention-fund-reservations.html
Labels: READY

#744 Financial Assurance/ Assessment Items
  pmp/app-elements/partners/assessments-items.html
  pmp/app-elements/partners/partner-financial-assurance.html
  pmp/app-elements/validators/required-and-not-future-date-validator.html
Labels: READY

#759 Fin assurance bug fixes
  pmp/app-elements/partners/assessments-items.html
  pmp/app-elements/partners/partner-financial-assurance.html
  pmp/app-elements/partners/partner-overview.html
Labels: READY

#761 Set contentContainer once
  pmp/modules/mixins/scroll-control-mixin.html
Labels: Polymer 2 migration, READY

#712 Polymer 2 Agreements
  .eslintrc.json
  .gitignore
  bower.json
  pmp/app-shell.html
  pmp/modules/app-modules/agreements/agreements-module.html
  pmp/modules/app-modules/agreements/components/agreement-status.html
  pmp/modules/app-modules/agreements/data/agreement-item-data.html
  pmp/modules/app-modules/agreements/data/agreements-list-data.html
  pmp/modules/app-modules/agreements/pages/details/agreement-details.html
  pmp/modules/app-modules/agreements/pages/details/components/agreement-amendments.html
  pmp/modules/app-modules/agreements/pages/details/components/generate-PCA-dialog.html
  pmp/modules/app-modules/agreements/pages/list/agreements-list.html
  pmp/modules/app-modules/mixins/module-common-mixin.html
  pmp/modules/app-modules/partners/mixins/staff-members-data-mixin.html
  pmp/modules/app-modules/partners/pages/list/partners-list.html
  pmp/modules/app-modules/partners/partners-module.html
  pmp/modules/endpoints/endpoints-mixin.html
  pmp/modules/environment-flags/environment-flags-mixin.html
  pmp/modules/layout/components/data-refresh-dialog.html
  pmp/modules/layout/components/etools-date-input.html
  pmp/modules/layout/components/etools-single-file.html
  pmp/modules/layout/menu/mixins/app-menu-mixin.html
  pmp/modules/layout/page-header.html
  pmp/modules/mixins/ajax-errors-parser-mixin.html
  pmp/modules/mixins/ajax-server-errors-mixin.html
  pmp/modules/mixins/amendment-mode-mixin.html
  pmp/modules/mixins/app-navigation-helper-mixin.html
  pmp/modules/mixins/array-helper-mixin.html
  pmp/modules/mixins/common-mixin.html
  pmp/modules/mixins/event-helper-mixin.html
  pmp/modules/mixins/ie11-mixin.html
  pmp/modules/mixins/list-data-mixin.html
  pmp/modules/mixins/list-filters-mixin.html
  pmp/modules/mixins/lists-common-mixin.html
  pmp/modules/mixins/missing-dropdown-options-mixin.html
  pmp/modules/mixins/pagination-mixin.html
  pmp/modules/mixins/repeatable-data-sets-mixin.html
  pmp/modules/mixins/risk-rating-mixin.html
  pmp/modules/mixins/scroll-control-mixin.html
  pmp/modules/mixins/utils-mixin.html
  pmp/modules/redux/etools-data-redux-store.html
  pmp/modules/styles/shared-styles.html
  pmp/modules/user/user-permissions-mixin.html
  pmp/modules/validators/etools-iron-validator-mixin.html
Labels: Polymer 2 migration, READY

#758 Migrate Financial Assurance functionality
  pmp/modules/app-modules/partners/pages/details/components/assessments-items.html
  pmp/modules/app-modules/partners/pages/details/partner-details.html
  pmp/modules/app-modules/partners/pages/financial-assurance/components/assessments-items.html
  pmp/modules/app-modules/partners/pages/financial-assurance/partner-financial-assurance.html
  pmp/modules/app-modules/partners/pages/overview/partner-overview.html
  pmp/modules/app-modules/partners/partners-module.html
  pmp/modules/config/app-constants.html
  pmp/modules/config/config.html
  pmp/modules/endpoints/endpoints.html
  pmp/modules/mixins/amendment-mode-mixin.html
  pmp/modules/mixins/repeatable-data-sets-mixin.html
  pmp/modules/validators/required-and-not-future-date-validator.html
  polymer.json
Labels: Polymer 2 migration, READY

#767 Sticky status improvements
  pmp/app-shell.html
  pmp/modules/app-modules/agreements/components/agreement-status.html
  pmp/modules/app-modules/partners/components/partner-status.html
  pmp/modules/layout/components/etools-status/etools-status-common-mixin.html
  pmp/modules/layout/components/etools-status/etools-status.html
  pmp/modules/styles/page-layout-styles.html
Labels: enhancement

#764 Fix status el position after refresh
  pmp/app-shell.html
  pmp/modules/app-modules/agreements/components/agreement-status.html
  pmp/modules/app-modules/partners/components/partner-status.html
  pmp/modules/layout/components/etools-status/etools-status-common-mixin.html
  pmp/modules/layout/components/etools-status/etools-status.html
  pmp/modules/styles/page-layout-styles.html
Labels: Polymer 2 migration, READY

#769 Add disaggregations button for PME users only
  pmp/app-config/app-user-permissions-behavior.html
  pmp/app-elements/interventions/expected-results/indicator-dialog.html
  pmp/app-elements/settings/disaggregation-list.html
Labels: READY

#772 add special cps to the list of agreement cps
  pmp/app-elements/agreements/agreement-details.html
Labels: READY

#768 List filters updates, ch#1880
  pmp/modules/app-modules/agreements/data/agreements-list-data.html
  pmp/modules/app-modules/agreements/pages/details/agreement-details.html
  pmp/modules/app-modules/agreements/pages/list/agreements-list.html
  pmp/modules/app-modules/partners/data/partners-list-data.html
  pmp/modules/app-modules/partners/pages/financial-assurance/partner-financial-assurance.html
  pmp/modules/app-modules/partners/pages/list/partners-list.html
  pmp/modules/mixins/lists-common-mixin.html
  pmp/modules/mixins/pagination-mixin.html
Labels: Polymer 2 migration, READY

#763 Updates to latest version of piwik element 1.x.x
  bower.json
Labels: READY

#773 Fix partner-status style from css variables
  pmp/app-shell.html
  pmp/modules/app-modules/agreements/components/agreement-status.html
  pmp/modules/app-modules/partners/components/partner-status.html
Labels: Polymer 2 migration, READY

#775 Fix etools-status transition
  pmp/modules/app-modules/partners/components/partner-status.html
  pmp/modules/app-modules/partners/pages/list/partners-list.html
  pmp/modules/layout/components/etools-status/etools-status-common-mixin.html
  pmp/modules/layout/components/etools-status/etools-status-styles.html
  pmp/modules/layout/components/etools-status/etools-status.html
  pmp/modules/styles/page-layout-styles.html
Labels: Polymer 2 migration, READY

#780 Fix sidebar menu transition from small to normal and vice versa
  pmp/modules/app-modules/agreements/agreements-module.html
  pmp/modules/app-modules/partners/pages/financial-assurance/partner-financial-assurance.html
  pmp/modules/layout/components/etools-status/etools-status-styles.html
  pmp/modules/layout/components/etools-status/etools-status.html
  pmp/modules/layout/menu/mixins/app-menu-mixin.html
  pmp/modules/layout/menu/styles/app-drawer-styles.html
  polymer.json
Labels: Polymer 2 migration, READY

#752 Lists filters updates, ch#1880
  pmp/app-behaviors/lists-common-behavior.html
  pmp/app-behaviors/pagination-behavior.html
  pmp/app-elements/agreements/agreement-data/agreement-list-data.html
  pmp/app-elements/agreements/agreements-list.html
  pmp/app-elements/interventions/interventions-list.html
  pmp/app-elements/partners/partner-financial-assurance.html
  pmp/app-elements/partners/partners-data/partners-list-data.html
  pmp/app-elements/partners/partners-list.html
Labels: API changes needed, READY, Wait for BE branch merge

#774 Delete agreements and PDs in draft status
  pmp/app-config/app-endpoints.html
  pmp/app-elements/agreements/agreement-data/agreement-item-data.html
  pmp/app-elements/agreements/agreement-status.html
  pmp/app-elements/etools-status/pmp-status-behavior.html
  pmp/app-elements/interventions/intervention-data/intervention-item-data.html
  pmp/app-elements/interventions/intervention-details.html
  pmp/app-elements/interventions/intervention-status.html
  pmp/app-shell.html
  pmp/pages/page-agreements.html
  pmp/pages/page-interventions.html
Labels: READY, Wait for BE branch merge

#782 fix planned budget edit issue on IE
  gulpfile.js
  package.json
  pmp/app-elements/agreements/agreement-data/agreement-item-data.html
  pmp/app-elements/interventions/intervention-data/intervention-item-data.html
  pmp/app-elements/interventions/intervention-planned-budget.html
  pmp/pages/page-interventions.html
  scripts/lodash/lodash.html
  scripts/polyfils/es6-polyfils.html
  scripts/redux.html
Labels: READY

#781 polymer2-add-disagregations-permissions:
  pmp/modules/app-modules/settings/components/disaggregation-list.html
  pmp/modules/user/user-permissions-mixin.html
Labels: Polymer 2 migration, READY

#779 Updated bower packages
  bower.json
Labels: READY

#783 Fix polymer2 duplicate profile requests
  pmp/app-shell.html
  pmp/modules/user/user-data-mixin.html
Labels: Polymer 2 migration, READY

#786 resets the engagements list when new partner detail loaded
  pmp/app-elements/partners/partner-financial-assurance.html
Labels: READY

#789 Feature delete agreement migration
  pmp/modules/app-modules/agreements/agreements-module.html
  pmp/modules/app-modules/agreements/components/agreement-status.html
  pmp/modules/app-modules/agreements/data/agreement-item-data.html
  pmp/modules/endpoints/endpoints.html
  pmp/modules/layout/components/etools-status/etools-status-common-mixin.html
  pmp/modules/scripts/lodash.html
  pmp/modules/scripts/redux.html
Labels: Polymer 2 migration, READY

#790 Migrate 'resets the engagements list when new partner detail loaded'
  pmp/modules/app-modules/partners/pages/financial-assurance/partner-financial-assurance.html
Labels: Polymer 2 migration, READY

#785 Alternative express server for bundled version
  express.js
  polymer.json
Labels: Polymer 2 migration, READY

#793 Clean up index.html
  index.html
Labels: Polymer 2 migration, READY

#784 Agreements export by multiple partners - ch#1880, Expired CP edit - ch#1499
  pmp/app-behaviors/pagination-behavior.html
  pmp/app-elements/agreements/agreement-details.html
  pmp/app-elements/agreements/agreements-list.html
  pmp/app-elements/common-elements/etools-cp-structure.html
  pmp/app-elements/interventions/intervention-details.html
Labels: READY

#791 updated pacakages versions
  bower.json
Labels: READY

#796 List filters height issue
  bower.json
  pmp/modules/layout/components/etools-date-input.html
Labels: READY

#795 Fix filter persistence issue
  pmp/app-behaviors/lists-common-behavior.html
Labels: READY
