Repository unicef/etools-partnership-management, pull requests merged in 2018-02, with the labels that each got.

#696 Fix scroll control error
  pmp/pages/page-reports.html
Labels: PRP-integration, READY

#698 Fix planned visits console error
  pmp/app-elements/interventions/intervention-planned-visits.html
Labels: READY

#697 Remove filter buttons
  pmp/app-behaviors/dropdown-behavior.html
  pmp/app-elements/agreements/agreements-list.html
  pmp/app-elements/interventions/amendments/add-amendment-dialog.html
  pmp/app-elements/interventions/interventions-list.html
  pmp/app-elements/partners/partners-list.html
Labels: PRP-integration, READY

#699 Migrate static-common-data to polymer2
  pmp/modules/redux/etools-data-redux-store.html
  pmp/modules/static-common-data/mixins/country-programmes-data.html
  pmp/modules/static-common-data/mixins/disaggregations-data.html
  pmp/modules/static-common-data/mixins/dropdowns-pmp-data.html
  pmp/modules/static-common-data/mixins/dropdowns-static-data.html
  pmp/modules/static-common-data/mixins/locations-data.html
  pmp/modules/static-common-data/mixins/offices-data.html
  pmp/modules/static-common-data/mixins/prp-countries.html
  pmp/modules/static-common-data/mixins/sections-data.html
  pmp/modules/static-common-data/mixins/sectors-data.html
  pmp/modules/static-common-data/mixins/unicef-users-data.html
  pmp/modules/static-common-data/mixins/user-country-data.html
  pmp/modules/static-common-data/static-common-data.html
Labels: READY

#692 Fix lingering reports query string
  pmp/app-elements/interventions/reports/intervention-reports.html
  pmp/app-shell.html
  pmp/pages/behaviors/subroute-behavior.html
  pmp/pages/page-interventions.html
Labels: PRP-integration, READY

#700 Fix missing agreement status
  pmp/pages/page-agreements.html
Labels: PRP-integration, READY

#701 missing-options behavior to mixin
  pmp/modules/mixins/date-mixin.html
  pmp/modules/mixins/missing-dropdown-options-mixin.html
Labels: READY

#703 app shell routing, other updates
  pmp/app-shell.html
  pmp/modules/app-modules/agreements/agreements-module.html
  pmp/modules/app-modules/interventions/interventions-module.html
  pmp/modules/app-modules/not-found/not-found.html
  pmp/modules/app-modules/partners/partners-module.html
  pmp/modules/app-modules/reports/reports-module.html
  pmp/modules/app-modules/settings/settings-module.html
  pmp/modules/layout/menu/app-sidebar-menu.html
  pmp/modules/layout/menu/mixins/app-menu-mixin.html
  pmp/modules/mixins/amendment-mode-mixin.html
  pmp/modules/mixins/scroll-control-mixin.html
Labels: Polymer 2 migration, READY

#704 app modules routing anf common functionality + fire event in polymer 2 style updates
  pmp/modules/app-modules/mixins/intervention-page-tabs-mixin.html
  pmp/modules/app-modules/mixins/module-common-mixin.html
  pmp/modules/app-modules/mixins/module-routing-mixin.html
  pmp/modules/mixins/ajax-server-errors-mixin.html
  pmp/modules/mixins/repeatable-data-sets-mixin.html
  pmp/modules/mixins/scroll-control-mixin.html
  pmp/modules/user/user-data.html
Labels: Polymer 2 migration, READY

#706 Partners module polymer 2 migration
  .eslintrc.json
  bower.json
  pmp/app-shell.html
  pmp/modules/app-modules/interventions/mixins/intervention-page-tabs-mixin.html
  pmp/modules/app-modules/mixins/module-routing-mixin.html
  pmp/modules/app-modules/partners/components/new-partner/new-partner-dialog.html
  pmp/modules/app-modules/partners/components/partner-status/partner-status.html
  pmp/modules/app-modules/partners/data/partner-item-data.html
  pmp/modules/app-modules/partners/pages/details/partner-details.html
  pmp/modules/app-modules/partners/pages/list/partners-list.html
  pmp/modules/app-modules/partners/pages/overview/partner-overview.html
  pmp/modules/app-modules/partners/partners-module.html
  pmp/modules/endpoints/endpoints-mixin.html
  pmp/modules/environment-flags/environment-flags-mixin.html
  pmp/modules/environment-flags/environment-flags.html
  pmp/modules/layout/components/etools-date-input.html
  pmp/modules/layout/components/etools-error-messages-box.html
  pmp/modules/layout/components/etools-single-file.html
  pmp/modules/layout/components/etools-status/etools-action-button.html
  pmp/modules/layout/components/etools-status/etools-status-common-mixin.html
  pmp/modules/layout/menu/app-sidebar-menu.html
  pmp/modules/layout/page-content-header/page-content-header-slotted-styles.html
  pmp/modules/layout/page-content-header/page-content-header.html
  pmp/modules/layout/page-header.html
  pmp/modules/mixins/common-mixin.html
  pmp/modules/mixins/date-mixin.html
  pmp/modules/mixins/list-data-mixin.html
  pmp/modules/mixins/missing-dropdown-options-mixin.html
  pmp/modules/mixins/repeatable-data-sets-mixin.html
  pmp/modules/mixins/scroll-control-mixin.html
  pmp/modules/mixins/utils-mixin.html
  pmp/modules/static-common-data/mixins/country-programmes-data.html
  pmp/modules/static-common-data/mixins/disaggregations-data.html
  pmp/modules/static-common-data/mixins/dropdowns-pmp-data.html
  pmp/modules/static-common-data/mixins/dropdowns-static-data.html
  pmp/modules/static-common-data/mixins/locations-data.html
  pmp/modules/static-common-data/mixins/offices-data.html
  pmp/modules/static-common-data/mixins/prp-countries.html
  pmp/modules/static-common-data/mixins/sections-data.html
  pmp/modules/static-common-data/mixins/sectors-data.html
  pmp/modules/static-common-data/mixins/unicef-users-data.html
  pmp/modules/static-common-data/mixins/user-country-data.html
  pmp/modules/static-common-data/static-common-data.html
  pmp/modules/toast-notifications/toast-notifications-mixin.html
  pmp/modules/user/user-data.html
  pmp/modules/validators/required-and-not-future-date-validator.html
  polymer.json
Labels: Polymer 2 migration, READY

#708 Fix disaggregations not displayed sometimes
  pmp/app-elements/settings/disaggregation-list.html
Labels: READY

#710 Polymer 2 event handlers update
  pmp/app-shell.html
  pmp/modules/app-modules/mixins/module-common-mixin.html
  pmp/modules/app-modules/mixins/module-routing-mixin.html
  pmp/modules/app-modules/not-found/not-found.html
  pmp/modules/app-modules/partners/data/partner-item-data.html
  pmp/modules/app-modules/partners/pages/list/partners-list.html
  pmp/modules/app-modules/partners/partners-module.html
  pmp/modules/layout/components/etools-status/etools-action-button.html
  pmp/modules/layout/menu/app-sidebar-menu.html
  pmp/modules/layout/page-header.html
  pmp/modules/mixins/ajax-errors-parser-mixin.html
  pmp/modules/mixins/ajax-server-errors-mixin.html
  pmp/modules/mixins/list-data-mixin.html
  pmp/modules/mixins/lists-common-mixin.html
  pmp/modules/mixins/repeatable-data-sets-mixin.html
  pmp/modules/user/user-data.html
Labels: Polymer 2 migration, READY

#702 Polymer 2 header migration
  .gitignore
  bower.json
  pmp/app-shell.html
  pmp/modules/app-modules/mixins/module-common-mixin.html
  pmp/modules/app-modules/mixins/module-routing-mixin.html
  pmp/modules/app-modules/not-found/not-found.html
  pmp/modules/app-modules/partners/data/partner-item-data.html
  pmp/modules/app-modules/partners/pages/list/partners-list.html
  pmp/modules/app-modules/partners/partners-module.html
  pmp/modules/config/dexie-db-config.html
  pmp/modules/layout/components/countries-dropdown.html
  pmp/modules/layout/components/data-refresh-dialog.html
  pmp/modules/layout/components/etools-status/etools-action-button.html
  pmp/modules/layout/menu/app-sidebar-menu.html
  pmp/modules/layout/page-header.html
  pmp/modules/mixins/ajax-errors-parser-mixin.html
  pmp/modules/mixins/ajax-server-errors-mixin.html
  pmp/modules/mixins/event-helper-mixin.html
  pmp/modules/mixins/list-data-mixin.html
  pmp/modules/mixins/lists-common-mixin.html
  pmp/modules/mixins/repeatable-data-sets-mixin.html
  pmp/modules/scripts/dexie.html
  pmp/modules/styles/buttons-styles.html
  pmp/modules/user/profile-operations-mixin.html
  pmp/modules/user/user-data-mixin.html
  pmp/modules/user/user-data.html
Labels: Polymer 2 migration, READY

#714 Fix timing issue on settings page
  pmp/app-elements/environment-flags/environment-flags-behavior.html
  pmp/app-elements/environment-flags/environment-flags.html
Labels: PRP-integration, READY

#709 New FRS validations
  bower.json
  pmp/app-elements/common-elements/etools-error-messages-box.html
  pmp/app-elements/interventions/behaviors/fr-numbers-consistency-behavior.html
  pmp/app-elements/interventions/behaviors/intervention-permissions-behavior.html
  pmp/app-elements/interventions/fr-numbers/fund-reservations-display.html
  pmp/app-elements/interventions/fr-numbers/intervention-fund-reservations.html
  pmp/app-elements/interventions/fr-numbers/styles/fr-warnings-styles.html
  pmp/app-elements/interventions/intervention-data/intervention-item-data.html
  pmp/app-elements/interventions/intervention-details.html
  pmp/app-elements/interventions/intervention-planned-budget.html
  pmp/app-elements/interventions/intervention-review-and-sign.html
  pmp/app-elements/interventions/interventions-list.html
  pmp/app-elements/partners/partner-overview.html
  styles/app-mixins.html
  styles/custom-iconsets/pmp-icons.html
  styles/shared-styles.html
Labels: PRP-integration, READY
