Repository unicef/etools-partnership-management, pull requests merged in 2018-10, with the labels that each got.

#1033 Add always visible filters in filters menu
  pmp/modules/app-modules/agreements/pages/list/agreements-list.html
  pmp/modules/app-modules/interventions/pages/list/interventions-list.html
  pmp/modules/app-modules/reports/pages/list/reports-list.html
  pmp/modules/mixins/list-filters-mixin.html
Labels: READY

#1034 Remove amendment mode ui in print mode
  pmp/app-shell.html
Labels: READY

#1035 Prp report fixes
  pmp/modules/app-modules/interventions/pages/progress/intervention-progress.html
  pmp/modules/app-modules/reports/pages/progress/components/disaggregations/disaggregation-table.html
  pmp/modules/app-modules/reports/pages/progress/components/indicator-report-target.html
  pmp/modules/app-modules/reports/pages/progress/components/sr-details.html
  pmp/modules/app-modules/reports/pages/progress/report-progress.html
  pmp/modules/app-modules/reports/pages/summary/report-summary.html
Labels: READY

#1036 Fix Reports filter issue
  pmp/modules/app-modules/reports/components/reports-display-list.html
Labels: READY

#1037 Fix intermittent 404 on get ram indicators
  pmp/modules/app-modules/reports/pages/progress/components/disaggregations/disaggregation-table.html
  pmp/modules/app-modules/reports/pages/progress/components/sr-details.html
  pmp/modules/app-modules/reports/pages/summary/report-summary.html
  pmp/modules/layout/components/etools-ram-indicators.html
Labels: READY

#1038 Prp report fixes 2
  pmp/modules/app-modules/reports/pages/progress/components/sr-details.html
  pmp/modules/app-modules/reports/pages/summary/report-summary.html
  pmp/modules/layout/components/etools-ram-indicators.html
Labels: READY

#1039 Update ratio indicator display
  pmp/modules/app-modules/interventions/pages/details/components/results/applied-indicator.html
  pmp/modules/app-modules/interventions/pages/details/components/results/mixins/save-indicator-mixin.html
Labels: READY

#1040 Update fields visibility for contingency pd
  pmp/modules/app-modules/interventions/pages/details/components/results/applied-indicator.html
  pmp/modules/app-modules/interventions/pages/details/intervention-details.html
Labels: READY

#1043 Partners filters menu added
  pmp/modules/app-modules/agreements/pages/list/agreements-list.html
  pmp/modules/app-modules/partners/pages/list/partners-list.html
  pmp/modules/mixins/list-filters-mixin.html
  pmp/modules/styles/list-filter-styles.html
Labels: READY

#1046 Update report progress values
  pmp/modules/app-modules/reports/pages/progress/components/indicator-details.html
  pmp/modules/app-modules/reports/pages/progress/components/indicator-report-target.html
  pmp/modules/app-modules/reports/pages/progress/report-progress.html
  pmp/modules/mixins/utils-mixin.html
Labels: READY

#1047 Fix add agreement amendment error
  pmp/modules/app-modules/agreements/data/agreement-item-data.html
Labels: READY

#1049 Clean up agreement code
  pmp/modules/app-modules/agreements/agreements-module.html
  pmp/modules/app-modules/agreements/data/agreement-item-data.html
  pmp/modules/app-modules/agreements/pages/details/agreement-details.html
Labels: READY

#1051 Update risk rating style
  pmp/modules/app-modules/partners/pages/overview/partner-overview.html
  pmp/modules/styles/risk-rating-styles.html
Labels: READY

#1053 Tweak progress values display
  pmp/modules/app-modules/reports/pages/progress/components/indicator-report-target.html
  pmp/modules/mixins/utils-mixin.html
Labels: READY

#1060 Use etools-upload for Agr./Signed Agreement att.
  bower.json
  pmp/modules/app-modules/agreements/agreements-module.html
  pmp/modules/app-modules/agreements/pages/details/agreement-details.html
  pmp/modules/app-modules/agreements/pages/details/components/amendments/add-ag-amendment-dialog.html
  pmp/modules/styles/required-field-styles.html
Labels: READY

#1056 partner assessments attachments updates to use new upload component
  pmp/modules/app-modules/partners/data/partner-item-data.html
  pmp/modules/app-modules/partners/pages/details/components/edit-core-values-assessment.html
  pmp/modules/app-modules/partners/pages/financial-assurance/components/assessments-items.html
  pmp/modules/app-modules/partners/pages/financial-assurance/partner-financial-assurance.html
  pmp/modules/app-modules/partners/partners-module.html
Labels: API changes needed, WIP

#1059 PD amendments upload functionality updates
  pmp/modules/app-modules/interventions/pages/review-and-sign/components/amendments/add-amendment-dialog.html
  pmp/modules/app-modules/interventions/pages/review-and-sign/components/amendments/pd-amendments.html
Labels: READY

#1058 Use etools-upload component for PD/Activation Letter
  pmp/modules/app-modules/interventions/interventions-module.html
  pmp/modules/app-modules/interventions/mixins/modified-intervention-fields-mixin.html
  pmp/modules/app-modules/interventions/mixins/save-intervention-mixin.html
  pmp/modules/app-modules/interventions/pages/details/intervention-details.html
Labels: API changes needed

#1061 PD termination notice updated to new upload functionality
  pmp/modules/app-modules/interventions/components/pd-termination.html
  pmp/modules/app-modules/interventions/pages/details/intervention-details.html
Labels: READY
