Repository unicef/etools-partnership-management, pull requests merged in 2018-11, with the labels that each got.

#1054 Partners new upload component integration
  pmp/modules/app-modules/partners/data/partner-item-data.html
  pmp/modules/app-modules/partners/pages/details/components/edit-core-values-assessment.html
  pmp/modules/app-modules/partners/pages/details/partner-details.html
  pmp/modules/app-modules/partners/pages/financial-assurance/components/assessments-items.html
  pmp/modules/app-modules/partners/pages/financial-assurance/partner-financial-assurance.html
  pmp/modules/app-modules/partners/partners-module.html
  pmp/modules/styles/required-field-styles.html
Labels: READY, Wait for BE branch merge

#1062 fixed sign pd validation
  pmp/modules/app-modules/interventions/pages/review-and-sign/intervention-review-and-sign.html
Labels: READY

#1065 Fix console error navigation
  pmp/modules/mixins/list-filters-mixin.html
Labels: READY

#1055 PD new upload component integration
  bower.json
  pmp/modules/app-modules/agreements/pages/details/agreement-details.html
  pmp/modules/app-modules/interventions/components/intervention-status.html
  pmp/modules/app-modules/interventions/components/pd-termination.html
  pmp/modules/app-modules/interventions/data/intervention-item-data.html
  pmp/modules/app-modules/interventions/interventions-module.html
  pmp/modules/app-modules/interventions/mixins/intervention-permissions-mixin.html
  pmp/modules/app-modules/interventions/mixins/modified-intervention-fields-mixin.html
  pmp/modules/app-modules/interventions/mixins/save-intervention-mixin.html
  pmp/modules/app-modules/interventions/pages/details/intervention-details.html
  pmp/modules/app-modules/interventions/pages/review-and-sign/components/amendments/add-amendment-dialog.html
  pmp/modules/app-modules/interventions/pages/review-and-sign/components/amendments/pd-amendments.html
  pmp/modules/app-modules/interventions/pages/review-and-sign/intervention-review-and-sign.html
  pmp/modules/app-modules/partners/pages/details/partner-details.html
  pmp/modules/layout/components/etools-status/etools-action-button.html
  pmp/modules/layout/components/etools-status/etools-status.html
  pmp/modules/mixins/uploads-mixin.html
  pmp/modules/redux/etools-data-redux-store.html
Labels: API changes needed, WIP, question

#1070 reset search filter
  pmp/modules/app-modules/partners/pages/list/partners-list.html
Labels: READY

#1071 Fix reports filters on data reset
  pmp/modules/app-modules/reports/pages/list/reports-list.html
  pmp/modules/layout/components/data-refresh-dialog.html
  pmp/modules/user/user-data-mixin.html
Labels: READY

#1072 fixed pd filter list styles for IE
  pmp/modules/app-modules/interventions/pages/list/interventions-list.html
  pmp/modules/styles/list-filter-styles.html
Labels: READY

#1081 Etools zendesk update
  index.html
  pmp/modules/layout/menu/app-sidebar-menu.html
Labels: READY

#1080 Updates script source for zendesk widget
  index.html
Labels: READY

#1078 fix update path method to avoid triggering route change events twice
  pmp/app-shell.html
Labels: READY

#1064 Updates to ratio indicator denominator
  pmp/modules/app-modules/interventions/pages/details/components/results/cluster-indicator.html
  pmp/modules/app-modules/interventions/pages/details/components/results/expected-results.html
  pmp/modules/app-modules/interventions/pages/details/components/results/indicator-dialog.html
  pmp/modules/app-modules/interventions/pages/details/components/results/non-cluster-indicator.html
Labels: READY

#1083 adjusted the agreements landing page
  pmp/modules/app-modules/agreements/pages/list/agreements-list.html
Labels: READY

#1067 Events listeners refactoring to prevent memory leaks
  pmp/app-shell.html
  pmp/modules/app-modules/agreements/agreements-module.html
  pmp/modules/app-modules/agreements/components/agreement-status.html
  pmp/modules/app-modules/agreements/pages/details/components/amendments/agreement-amendments.html
  pmp/modules/app-modules/interventions/components/intervention-status.html
  pmp/modules/app-modules/interventions/interventions-module.html
  pmp/modules/app-modules/interventions/mixins/intervention-permissions-mixin.html
  pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/hr/humanitarian-reporting-req-unicef.html
  pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/qpr/quarterly-reporting-requirements.html
  pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/srr/special-reporting-requirements.html
  pmp/modules/app-modules/interventions/pages/details/components/results/applied-indicator.html
  pmp/modules/app-modules/interventions/pages/details/components/results/expected-results.html
  pmp/modules/app-modules/interventions/pages/details/components/results/indicator-dialog.html
  pmp/modules/app-modules/interventions/pages/details/components/results/mixins/lower-results-mixin.html
  pmp/modules/app-modules/interventions/pages/details/components/results/mixins/results-mixin.html
  pmp/modules/app-modules/interventions/pages/details/components/results/result-link-lower-results.html
  pmp/modules/app-modules/interventions/pages/review-and-sign/components/amendments/pd-amendments.html
  pmp/modules/app-modules/interventions/pages/review-and-sign/components/fund-reservations/fund-reservations.html
  pmp/modules/app-modules/mixins/module-common-mixin.html
  pmp/modules/app-modules/mixins/module-routing-mixin.html
  pmp/modules/app-modules/partners/components/partner-status.html
  pmp/modules/app-modules/partners/pages/details/components/staff-members.html
  pmp/modules/app-modules/partners/partners-module.html
  pmp/modules/app-modules/reports/pages/progress/components/disaggregations/disaggregation-field.html
  pmp/modules/app-modules/reports/reports-module.html
  pmp/modules/layout/components/etools-status/etools-status-common-mixin.html
  pmp/modules/layout/menu/mixins/app-menu-mixin.html
  pmp/modules/mixins/lists-common-mixin.html
  pmp/modules/mixins/repeatable-data-sets-mixin.html
  pmp/modules/toast-notifications/toast-notifications-mixin.html
Labels: On hold, READY

#1063 Reports new upload component integration
  pmp/app-shell.html
  pmp/modules/app-modules/agreements/agreements-module.html
  pmp/modules/app-modules/agreements/components/agreement-status.html
  pmp/modules/app-modules/agreements/pages/details/components/amendments/agreement-amendments.html
  pmp/modules/app-modules/interventions/components/intervention-status.html
  pmp/modules/app-modules/interventions/interventions-module.html
  pmp/modules/app-modules/interventions/mixins/intervention-permissions-mixin.html
  pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/hr/humanitarian-reporting-req-unicef.html
  pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/qpr/quarterly-reporting-requirements.html
  pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/srr/special-reporting-requirements.html
  pmp/modules/app-modules/interventions/pages/details/components/results/applied-indicator.html
  pmp/modules/app-modules/interventions/pages/details/components/results/expected-results.html
  pmp/modules/app-modules/interventions/pages/details/components/results/indicator-dialog.html
  pmp/modules/app-modules/interventions/pages/details/components/results/mixins/lower-results-mixin.html
  pmp/modules/app-modules/interventions/pages/details/components/results/mixins/results-mixin.html
  pmp/modules/app-modules/interventions/pages/details/components/results/result-link-lower-results.html
  pmp/modules/app-modules/interventions/pages/review-and-sign/components/amendments/pd-amendments.html
  pmp/modules/app-modules/interventions/pages/review-and-sign/components/fund-reservations/fund-reservations.html
  pmp/modules/app-modules/mixins/module-common-mixin.html
  pmp/modules/app-modules/mixins/module-routing-mixin.html
  pmp/modules/app-modules/partners/components/partner-status.html
  pmp/modules/app-modules/partners/pages/details/components/staff-members.html
  pmp/modules/app-modules/partners/partners-module.html
  pmp/modules/app-modules/reports/pages/progress/components/disaggregations/disaggregation-field.html
  pmp/modules/app-modules/reports/pages/progress/components/sr-details.html
  pmp/modules/app-modules/reports/pages/summary/report-summary.html
  pmp/modules/app-modules/reports/reports-module.html
  pmp/modules/layout/components/etools-single-file.html
  pmp/modules/layout/components/etools-status/etools-status-common-mixin.html
  pmp/modules/layout/menu/mixins/app-menu-mixin.html
  pmp/modules/mixins/lists-common-mixin.html
  pmp/modules/mixins/repeatable-data-sets-mixin.html
  pmp/modules/styles/required-field-styles.html
  pmp/modules/toast-notifications/toast-notifications-mixin.html
Labels: On hold, READY

#1073 Send only modified data as payload for new PD request
  pmp/modules/app-modules/interventions/interventions-module.html
  pmp/modules/app-modules/interventions/mixins/save-intervention-mixin.html
Labels: READY

#1069 Handle leave page when upload unsaved or in progress
  pmp/app-shell.html
  pmp/modules/app-modules/agreements/agreements-module.html
  pmp/modules/app-modules/interventions/interventions-module.html
  pmp/modules/app-modules/interventions/mixins/save-intervention-mixin.html
  pmp/modules/app-modules/interventions/pages/reports/intervention-reports.html
  pmp/modules/app-modules/mixins/module-common-mixin.html
  pmp/modules/app-modules/mixins/module-routing-mixin.html
  pmp/modules/layout/components/data-refresh-dialog.html
  pmp/modules/layout/components/etools-status/etools-status.html
  pmp/modules/mixins/utils-mixin.html
Labels: READY

#1052 Agreements new upload component integration
  bower.json
  pmp/app-shell.html
  pmp/modules/app-modules/agreements/agreements-module.html
  pmp/modules/app-modules/agreements/components/agreement-status.html
  pmp/modules/app-modules/agreements/data/agreement-item-data.html
  pmp/modules/app-modules/agreements/pages/details/agreement-details.html
  pmp/modules/app-modules/agreements/pages/details/components/amendments/add-ag-amendment-dialog.html
  pmp/modules/app-modules/agreements/pages/details/components/amendments/agreement-amendments.html
  pmp/modules/app-modules/interventions/components/intervention-status.html
  pmp/modules/app-modules/interventions/components/pd-termination.html
  pmp/modules/app-modules/interventions/data/intervention-item-data.html
  pmp/modules/app-modules/interventions/interventions-module.html
  pmp/modules/app-modules/interventions/mixins/intervention-permissions-mixin.html
  pmp/modules/app-modules/interventions/mixins/modified-intervention-fields-mixin.html
  pmp/modules/app-modules/interventions/mixins/save-intervention-mixin.html
  pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/hr/humanitarian-reporting-req-unicef.html
  pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/qpr/quarterly-reporting-requirements.html
  pmp/modules/app-modules/interventions/pages/details/components/reporting-requirements/srr/special-reporting-requirements.html
  pmp/modules/app-modules/interventions/pages/details/components/results/applied-indicator.html
  pmp/modules/app-modules/interventions/pages/details/components/results/expected-results.html
  pmp/modules/app-modules/interventions/pages/details/components/results/indicator-dialog.html
  pmp/modules/app-modules/interventions/pages/details/components/results/mixins/lower-results-mixin.html
  pmp/modules/app-modules/interventions/pages/details/components/results/mixins/results-mixin.html
  pmp/modules/app-modules/interventions/pages/details/components/results/result-link-lower-results.html
  pmp/modules/app-modules/interventions/pages/details/intervention-details.html
  pmp/modules/app-modules/interventions/pages/reports/intervention-reports.html
  pmp/modules/app-modules/interventions/pages/review-and-sign/components/amendments/add-amendment-dialog.html
  pmp/modules/app-modules/interventions/pages/review-and-sign/components/amendments/pd-amendments.html
  pmp/modules/app-modules/interventions/pages/review-and-sign/components/fund-reservations/fund-reservations.html
  pmp/modules/app-modules/interventions/pages/review-and-sign/intervention-review-and-sign.html
  pmp/modules/app-modules/mixins/module-common-mixin.html
  pmp/modules/app-modules/mixins/module-routing-mixin.html
  pmp/modules/app-modules/partners/components/partner-status.html
  pmp/modules/app-modules/partners/data/partner-item-data.html
  pmp/modules/app-modules/partners/pages/details/components/edit-core-values-assessment.html
  pmp/modules/app-modules/partners/pages/details/components/staff-members.html
  pmp/modules/app-modules/partners/pages/details/partner-details.html
  pmp/modules/app-modules/partners/pages/financial-assurance/components/assessments-items.html
  pmp/modules/app-modules/partners/pages/financial-assurance/partner-financial-assurance.html
  pmp/modules/app-modules/partners/partners-module.html
  pmp/modules/app-modules/reports/pages/progress/components/disaggregations/disaggregation-field.html
  pmp/modules/app-modules/reports/pages/progress/components/sr-details.html
  pmp/modules/app-modules/reports/pages/summary/report-summary.html
  pmp/modules/app-modules/reports/reports-module.html
  pmp/modules/layout/components/data-refresh-dialog.html
  pmp/modules/layout/components/etools-single-file.html
  pmp/modules/layout/components/etools-status/etools-action-button.html
  pmp/modules/layout/components/etools-status/etools-status-common-mixin.html
  pmp/modules/layout/components/etools-status/etools-status.html
  pmp/modules/layout/menu/mixins/app-menu-mixin.html
  pmp/modules/mixins/lists-common-mixin.html
  pmp/modules/mixins/repeatable-data-sets-mixin.html
  pmp/modules/mixins/uploads-mixin.html
  pmp/modules/mixins/utils-mixin.html
  pmp/modules/redux/etools-data-redux-store.html
  pmp/modules/styles/required-field-styles.html
  pmp/modules/toast-notifications/toast-notifications-mixin.html
Labels: READY

#1086 Hide Disaggregation label for cluster indicator
  pmp/modules/app-modules/interventions/pages/details/components/results/applied-indicator.html
Labels: READY

#1085 Prepopulate target denominator for ratio cluster indicator
  pmp/modules/app-modules/interventions/pages/details/components/results/cluster-indicator.html
Labels: READY

#1087 Fix baseline negative number
  pmp/modules/app-modules/interventions/pages/details/components/results/non-cluster-indicator.html
Labels: READY

#1088 Fix intervention-progress target display
  pmp/modules/app-modules/interventions/pages/progress/intervention-progress.html
  pmp/modules/layout/components/etools-progress-bar.html
Labels: READY

#1089 Update Location progress display
  pmp/modules/app-modules/reports/pages/progress/components/indicator-details.html
  pmp/modules/mixins/utils-mixin.html
Labels: READY

#1090 PD save fix for ref year
  pmp/modules/app-modules/interventions/interventions-module.html
  pmp/modules/app-modules/interventions/pages/details/intervention-details.html
Labels: READY

#1091 fixed missing required symbol on signed date field
  pmp/modules/app-modules/agreements/pages/details/components/amendments/add-ag-amendment-dialog.html
  pmp/modules/app-modules/interventions/pages/review-and-sign/components/amendments/add-amendment-dialog.html
Labels: READY

#1092 Fix existing partner assessments updates
  pmp/modules/app-modules/partners/partners-module.html
Labels: READY

#1093 fixed export button style
  pmp/modules/app-modules/reports/reports-module.html
Labels: READY

#1094 Fix Edge date conversion issue
  pmp/modules/app-modules/interventions/pages/progress/intervention-progress.html
  pmp/modules/mixins/date-mixin.html
Labels: READY

#1095 Handle indexeddb DatabaseClosedError
  pmp/modules/app-modules/agreements/data/agreements-list-data.html
  pmp/modules/app-modules/interventions/data/interventions-list-data.html
  pmp/modules/app-modules/partners/data/partners-list-data.html
Labels: READY

#1096 Update etools-upload version
  bower.json
Labels: READY

#1097 Fix dropdown issues & tooltips delay
  bower.json
  pmp/modules/app-modules/interventions/pages/details/components/results/cluster-indicator.html
  pmp/modules/app-modules/interventions/pages/details/components/results/indicator-dialog.html
  pmp/modules/app-modules/interventions/pages/details/components/results/non-cluster-indicator.html
  pmp/modules/styles/app-theme.html
Labels: READY

#1103 Fix show delete button
  pmp/modules/app-modules/agreements/pages/details/agreement-details.html
Labels: READY

#1104 fixed position required field on partner contacts dialog
  pmp/modules/app-modules/partners/pages/details/components/add-edit-staff-members.html
Labels: READY

#1105 No upload warning on refresh data
  pmp/modules/layout/components/data-refresh-dialog.html
Labels: READY

#1099 Fix planned budget aligment
  pmp/modules/app-modules/interventions/pages/details/components/planned-budget.html
Labels: READY

#1106 Edge fix on country changed in another browser
  pmp/modules/app-modules/agreements/data/agreements-list-data.html
  pmp/modules/app-modules/interventions/data/interventions-list-data.html
  pmp/modules/app-modules/partners/data/partners-list-data.html
Labels: READY

#1107 fixed intervention validation
  pmp/modules/app-modules/interventions/pages/review-and-sign/intervention-review-and-sign.html
Labels: READY

#1098 added search input for disaggregations and a toggle switch for active
  pmp/modules/app-modules/settings/components/add-disaggregation-dialog.html
  pmp/modules/app-modules/settings/components/disaggregation-list.html
  pmp/modules/endpoints/endpoints.html
  pmp/modules/mixins/frontend-pagination-mixin.html
  pmp/modules/redux/etools-data-redux-store.html
  pmp/modules/static-common-data/static-common-data.html
Labels: WIP

#1109 fixed info button click issue
  pmp/modules/layout/components/etools-status/etools-action-button.html
Labels: READY

#1111 Cluster indicator fixes
  pmp/modules/app-modules/interventions/pages/details/components/results/cluster-indicator.html
  pmp/modules/app-modules/interventions/pages/details/components/results/expected-results.html
  pmp/modules/app-modules/interventions/pages/details/components/results/non-cluster-indicator.html
  pmp/modules/styles/required-field-styles.html
Labels: READY

#1112 Reset upload flags on del assessment
  pmp/app-shell.html
  pmp/modules/app-modules/partners/pages/financial-assurance/components/assessments-items.html
  pmp/modules/mixins/uploads-mixin.html
Labels: READY

#1110 Fix disaggreg dropdown
  pmp/modules/app-modules/interventions/pages/details/components/results/indicator-dissaggregations.html
Labels: READY

#1100 PD attachments redesign
  pmp/modules/app-modules/interventions/interventions-module.html
  pmp/modules/app-modules/interventions/pages/attachments/components/attachment-dialog.html
  pmp/modules/app-modules/interventions/pages/attachments/intervention-attachments.html
  pmp/modules/app-modules/interventions/pages/review-and-sign/components/amendments/add-amendment-dialog.html
  pmp/modules/app-modules/partners/pages/details/components/staff-members.html
  pmp/modules/endpoints/endpoints.html
  pmp/modules/styles/etools-cp-header-actions-bar-styles.html
Labels: READY, Wait for BE branch merge

#1115 Edge style fix for expected results
  pmp/modules/app-modules/interventions/pages/details/components/results/result-link-lower-results.html
Labels: READY

#1117 Fix edge style issue on partner pages
  pmp/modules/app-modules/interventions/pages/list/interventions-list.html
  pmp/modules/app-modules/partners/pages/details/partner-details.html
  pmp/modules/app-modules/partners/pages/financial-assurance/components/assessments-items.html
  pmp/modules/app-modules/partners/pages/financial-assurance/partner-financial-assurance.html
  pmp/modules/app-modules/partners/pages/overview/partner-overview.html
  pmp/modules/mixins/risk-rating-mixin.html
Labels: READY

#1119 Fix progress-bar value not shown in Edge
  pmp/modules/app-modules/interventions/pages/progress/intervention-progress.html
  pmp/modules/mixins/date-mixin.html
Labels: READY

#1118 etools-file cleanup
  bower.json
  pmp/modules/app-modules/agreements/pages/details/components/amendments/add-ag-amendment-dialog.html
  pmp/modules/app-modules/interventions/components/pd-termination.html
  pmp/modules/app-modules/interventions/pages/review-and-sign/intervention-review-and-sign.html
  pmp/modules/app-modules/partners/pages/details/partner-details.html
  pmp/modules/app-modules/partners/pages/financial-assurance/components/assessments-items.html
  pmp/modules/styles/app-theme.html
  pmp/modules/styles/file-styles.html
  pmp/modules/styles/required-field-styles.html
Labels: READY

#1116 Fix edge style issue for agreement details
  pmp/modules/app-modules/agreements/pages/details/agreement-details.html
Labels: READY

#1120 Update etools-behaviors version
  bower.json
  pmp/modules/layout/components/data-refresh-dialog.html
Labels: READY

#1121 Fix partner contacts display in Edge
  pmp/modules/app-modules/partners/pages/details/components/staff-members.html
Labels: READY

#1122 Edge fix for dynamically applying css classes
  pmp/modules/app-modules/interventions/pages/details/components/planned-visits.html
  pmp/modules/app-modules/interventions/pages/overview/components/fund-reservations-display.html
  pmp/modules/app-modules/reports/pages/progress/report-progress.html
  pmp/modules/layout/components/etools-form-element-wrapper.html
  pmp/modules/layout/components/etools-status/etools-status.html
Labels: READY

#1123 Fix date comparison
  pmp/modules/app-modules/interventions/pages/progress/intervention-progress.html
  pmp/modules/mixins/date-mixin.html
Labels: READY
